New Gift ClickOnce
sciooga/v2ex-plus pull request #64
Opened 2017-07-21 02:55 UTC by p0we7

2017-07-21 02:57 UTC, gloomy-ghost commented
Have we worked out the license issue?

2017-07-22 02:16 UTC, xhhjin requested changes
FF上可以签到了，但效果还不完整。

2017-07-22 02:16 UTC, xhhjin commented on v2ex_tab.js
> +        giftLink = ("https://www.v2ex.com/mission/daily/redeem" + RegExp("/signout(\\?once=[0-9]+)").exec($('div#Top').html())[1]);
因为V站有多个域名，比如：https://cn.v2ex.com/ ，所以尽量不要直接写死域名，建议改成：giftLink = (location.origin + "/mission/daily/redeem" + RegExp("/signout(\\?once=[0-9]+)").exec($('div#Top').html())[1]);

2017-07-22 02:16 UTC, xhhjin commented on v2ex_tab.js
> +            $.get('/balance', function(result) {
此处也要用绝对URL，可改为：$.get(location.origin + '/balance', function(result) {

2017-07-22 05:07 UTC, xhhjin approved these changes

2017-07-23 06:14 UTC, merged